lp-gw - overhauled tc script, implemented in lp-gw

diff --git a/lp-gw/templates/tc.j2 b/lp-gw/templates/tc.j2
--- a/lp-gw/templates/tc.j2
+++ b/lp-gw/templates/tc.j2
@@ -1,27 +1,11 @@
 #! /bin/sh
 
-### BEGIN INIT INFO
-# Provides:             tc
-# Required-Start:       $remote_fs $syslog $network
-# Required-Stop:        $remote_fs $syslog $network
-# Default-Start:        2 3 4 5
-# Default-Stop:
-# Short-Description:    TC ruleset provider
-### END INIT INFO
+IFACE="$2"
 
-set -e
-
-# /etc/init.d/tc: Manage TC ruleset
-
-DOWNLOAD_IFACE="{{ isp_if.lan }}"
-UPLOAD_IFACE="{{ isp_if.wan }}"
-
-# Interface maximum speed
-IFACE_MAX="{{ isp_rate.iface }}"
-# Maximum download speed (speedtest.net speed)
-DOWNLOAD_MAX="{{ isp_rate.down }}"
-# Maximum upload speed (speedtest.net speed)
-UPLOAD_MAX="{{ isp_rate.up }}"
+# (Ethernet) Interface Speed
+ETH_RATE="1000000"
+# Internet Line Rate
+INET_MAX="$3"
 
 TC="/sbin/tc"
 PY="/usr/bin/python2.7"
@@ -37,187 +21,99 @@ QOS_RATIO_C2="0.85" # Maximum internet speed
     QOS_RATIO_C23="0.20" # Crew
 QOS_RATIO_C3="0.2" # Reserved for interface communication (e.g. L2, routing protocols)
 
-QOS_DOWNLOAD_C1=${IFACE_MAX} # Maximum interface speed
-  QOS_DOWNLOAD_C2=`$PY -c 'from math import ceil; print "%.0f" % ceil('${DOWNLOAD_MAX}' * '${QOS_RATIO_C2}')'` # Maximum internet speed
-    QOS_DOWNLOAD_C11=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C2}' * '${QOS_RATIO_C11}')'` # Priority 1
-    QOS_DOWNLOAD_C12=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C2}' * '${QOS_RATIO_C12}')'` # Priority 2
-    QOS_DOWNLOAD_C13=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C2}' * '${QOS_RATIO_C13}')'` # Other
-      QOS_DOWNLOAD_C21=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C13}' * '${QOS_RATIO_C21}')'` # tcp/80, tcp/443, tcp/21
-        QOS_DOWNLOAD_C31=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C21}' * '${QOS_RATIO_C31}')'` # Browsing
-        QOS_DOWNLOAD_C32=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C21}' * '${QOS_RATIO_C32}')'` # Downloading
-      QOS_DOWNLOAD_C22=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C13}' * '${QOS_RATIO_C22}')'` # Thrash
-      QOS_DOWNLOAD_C23=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_DOWNLOAD_C13}' * '${QOS_RATIO_C23}')'` # Crew
-  QOS_DOWNLOAD_C3=`$PY -c 'from math import ceil; print "%.0f" % ceil('${IFACE_MAX}' * '${QOS_RATIO_C3}')'` # Reserved for interface communication (e.g. L2, routing protocols)
-
-QOS_UPLOAD_C1=${IFACE_MAX} # Maximum interface speed
-  QOS_UPLOAD_C2=`$PY -c 'from math import ceil; print "%.0f" % ceil('${UPLOAD_MAX}' * '${QOS_RATIO_C2}')'` # Maximum internet speed
-    QOS_UPLOAD_C11=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C2}' * '${QOS_RATIO_C11}')'` # Priority 1
-    QOS_UPLOAD_C12=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C2}' * '${QOS_RATIO_C12}')'` # Priority 2
-    QOS_UPLOAD_C13=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C2}' * '${QOS_RATIO_C13}')'` # Other
-      QOS_UPLOAD_C21=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C13}' * '${QOS_RATIO_C21}')'` # tcp/80, tcp/443, tcp/21
-        QOS_UPLOAD_C31=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C21}' * '${QOS_RATIO_C31}')'` # Browsing
-        QOS_UPLOAD_C32=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C21}' * '${QOS_RATIO_C32}')'` # Downloading
-      QOS_UPLOAD_C22=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C13}' * '${QOS_RATIO_C22}')'` # Thrash
-      QOS_UPLOAD_C23=`$PY -c 'from math import ceil; print "%.0f" % ceil('${QOS_UPLOAD_C13}' * '${QOS_RATIO_C23}')'` # Crew
-  QOS_UPLOAD_C3=`$PY -c 'from math import ceil; print "%.0f" % ceil('${IFACE_MAX}' * '${QOS_RATIO_C3}')'` # Reserved for interface communication (e.g. L2, routing protocols)
-
-umask 022
-
-. /lib/lsb/init-functions
-
-tc_check() {
-  $TC qdisc show | grep "fq_codel" > /dev/null
-}
-
 tc_flush() {
-$TC qdisc del dev ${UPLOAD_IFACE} root
-$TC qdisc del dev ${DOWNLOAD_IFACE} root
-return 0
+  $TC qdisc del dev ${IFACE} root
+  return 0
 }
 
 tc_commit() {
-echo ${QOS_DOWNLOAD_C1}' / '${QOS_UPLOAD_C1}' | Maximum interface speed'
-echo '   '${QOS_DOWNLOAD_C2}' / '${QOS_UPLOAD_C2}' | Maximum internet speed'
-echo '       '${QOS_DOWNLOAD_C11}' / '${QOS_UPLOAD_C11}' | Priority 1 | DSCP AF41'
-echo '       '${QOS_DOWNLOAD_C12}' / '${QOS_UPLOAD_C12}' | Priority 2 | DSCP AF42'
-echo '       '${QOS_DOWNLOAD_C13}' / '${QOS_UPLOAD_C13}' | Other'
-echo '           '${QOS_DOWNLOAD_C21}' / '${QOS_UPLOAD_C21}' | tcp/80, tcp/443, tcp/21'
-echo '               '${QOS_DOWNLOAD_C31}' / '${QOS_UPLOAD_C31}' | Browsing | DSCP AF31'
-echo '               '${QOS_DOWNLOAD_C32}' / '${QOS_UPLOAD_C32}' | Downloading | DSCP AF32'
-echo '           '${QOS_DOWNLOAD_C22}' / '${QOS_UPLOAD_C22}' | Thrash | DSCP Best Effort'
-echo '           '${QOS_DOWNLOAD_C23}' / '${QOS_UPLOAD_C23}' | Crew | DSCP AF21'
-echo '   '${QOS_DOWNLOAD_C3}' / '${QOS_UPLOAD_C3}' | Reserved for interface communication'
 
-$TC qdisc add dev ${UPLOAD_IFACE} stab linklayer ethernet mtu 1500 root handle 1: hfsc default 3
-$TC class add dev ${UPLOAD_IFACE} parent 1: classid 1:1 hfsc sc rate ${QOS_UPLOAD_C1}kbit ul rate ${QOS_UPLOAD_C1}kbit
-$TC class add dev ${UPLOAD_IFACE} parent 1:1 classid 1:2 hfsc sc rate ${QOS_UPLOAD_C2}kbit ul rate ${QOS_UPLOAD_C2}kbit
-  $TC class add dev ${UPLOAD_IFACE} parent 1:2 classid 1:11 hfsc sc rate ${QOS_UPLOAD_C11}kbit
-    $TC qdisc add dev ${UPLOAD_IFACE} parent 1:11 handle 11: fq_codel noecn limit 1200 flows 65535 target 5ms
-  $TC class add dev ${UPLOAD_IFACE} parent 1:2 classid 1:12 hfsc sc dmax 60ms rate ${QOS_UPLOAD_C12}kbit
-    $TC qdisc add dev ${UPLOAD_IFACE} parent 1:12 handle 12: fq_codel noecn limit 1200 flows 65535 target 5ms
-  $TC class add dev ${UPLOAD_IFACE} parent 1:2 classid 1:13 hfsc ls dmax 100ms rate ${QOS_UPLOAD_C13}kbit
-    $TC class add dev ${UPLOAD_IFACE} parent 1:13 classid 1:21 hfsc ls rate ${QOS_UPLOAD_C21}kbit
-      $TC class add dev ${UPLOAD_IFACE} parent 1:21 classid 1:31 hfsc sc rate ${QOS_UPLOAD_C31}kbit
-        $TC qdisc add dev ${UPLOAD_IFACE} parent 1:31 handle 31: fq_codel noecn limit 1200 flows 65535 target 5ms
-      $TC class add dev ${UPLOAD_IFACE} parent 1:21 classid 1:32 hfsc ls dmax 10ms rate ${QOS_UPLOAD_C32}kbit
-        $TC qdisc add dev ${UPLOAD_IFACE} parent 1:32 handle 32: fq_codel noecn limit 1200 flows 65535 target 5ms
-    $TC class add dev ${UPLOAD_IFACE} parent 1:13 classid 1:22 hfsc ls dmax 50ms rate ${QOS_UPLOAD_C22}kbit
-      $TC qdisc add dev ${UPLOAD_IFACE} parent 1:22 handle 22: fq_codel noecn limit 1200 flows 65535 target 5ms
-    $TC class add dev ${UPLOAD_IFACE} parent 1:13 classid 1:23 hfsc ls rate ${QOS_UPLOAD_C23}kbit
-      $TC qdisc add dev ${UPLOAD_IFACE} parent 1:23 handle 23: fq_codel noecn limit 1200 flows 65535 target 5ms
-$TC class add dev ${UPLOAD_IFACE} parent 1:1 classid 1:3 hfsc ls rate ${QOS_UPLOAD_C3}kbit
-  $TC qdisc add dev ${UPLOAD_IFACE} parent 1:3 handle 3: fq_codel noecn limit 1200 flows 65535 target 5ms
+if [ -z "$INET_MAX" ]; then
+  echo "Target rate is not specified, aborting."
+  exit 1
+fi
 
-$TC filter add dev ${UPLOAD_IFACE} parent 1: protocol arp basic classid 1:3
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 11 fw classid 1:11 # DSCP AF41
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 12 fw classid 1:12 # DSCP AF42
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 31 fw classid 1:31 # DSCP AF31
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 32 fw classid 1:32 # DSCP AF32
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 22 fw classid 1:22 # DSCP Best Effort
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 23 fw classid 1:23 # DSCP AF21
-$TC filter add dev ${UPLOAD_IFACE} parent 1: handle 3 fw classid 1:3
+RATE_C1=${ETH_RATE} # Maximum interface speed
+  RATE_C2=`$PY -c 'from math import ceil; print "%.0f" % ceil('${INET_MAX}' * '${QOS_RATIO_C2}')'` # Maximum internet speed
+    RATE_C11=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C2}' * '${QOS_RATIO_C11}')'` # Priority 1
+    RATE_C12=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C2}' * '${QOS_RATIO_C12}')'` # Priority 2
+    RATE_C13=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C2}' * '${QOS_RATIO_C13}')'` # Other
+      RATE_C21=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C13}' * '${QOS_RATIO_C21}')'` # tcp/80, tcp/443, tcp/21
+        RATE_C31=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C21}' * '${QOS_RATIO_C31}')'` # Browsing
+        RATE_C32=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C21}' * '${QOS_RATIO_C32}')'` # Downloading
+      RATE_C22=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C13}' * '${QOS_RATIO_C22}')'` # Thrash
+      RATE_C23=`$PY -c 'from math import ceil; print "%.0f" % ceil('${RATE_C13}' * '${QOS_RATIO_C23}')'` # Crew
+  RATE_C3=`$PY -c 'from math import ceil; print "%.0f" % ceil('${ETH_RATE}' * '${QOS_RATIO_C3}')'` # Reserved for interface communication (e.g. L2, routing protocols)
 
-$TC qdisc add dev ${DOWNLOAD_IFACE} stab linklayer ethernet mtu 1500 root handle 1: hfsc default 3
-$TC class add dev ${DOWNLOAD_IFACE} parent 1: classid 1:1 hfsc sc rate ${QOS_DOWNLOAD_C1}kbit ul rate ${QOS_DOWNLOAD_C1}kbit
-$TC class add dev ${DOWNLOAD_IFACE} parent 1:1 classid 1:2 hfsc sc rate ${QOS_DOWNLOAD_C2}kbit ul rate ${QOS_DOWNLOAD_C2}kbit
-  $TC class add dev ${DOWNLOAD_IFACE} parent 1:2 classid 1:11 hfsc sc rate ${QOS_DOWNLOAD_C11}kbit
-    $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:11 handle 11: fq_codel noecn limit 1200 flows 65535 target 5ms
-  $TC class add dev ${DOWNLOAD_IFACE} parent 1:2 classid 1:12 hfsc sc dmax 60ms rate ${QOS_DOWNLOAD_C12}kbit
-    $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:12 handle 12: fq_codel noecn limit 1200 flows 65535 target 5ms
-  $TC class add dev ${DOWNLOAD_IFACE} parent 1:2 classid 1:13 hfsc ls dmax 100ms rate ${QOS_DOWNLOAD_C13}kbit
-    $TC class add dev ${DOWNLOAD_IFACE} parent 1:13 classid 1:21 hfsc ls rate ${QOS_DOWNLOAD_C21}kbit
-      $TC class add dev ${DOWNLOAD_IFACE} parent 1:21 classid 1:31 hfsc sc rate ${QOS_DOWNLOAD_C31}kbit
-        $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:31 handle 31: fq_codel noecn limit 1200 flows 65535 target 5ms
-      $TC class add dev ${DOWNLOAD_IFACE} parent 1:21 classid 1:32 hfsc ls dmax 10ms rate ${QOS_DOWNLOAD_C32}kbit
-        $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:32 handle 32: fq_codel noecn limit 1200 flows 65535 target 5ms
-    $TC class add dev ${DOWNLOAD_IFACE} parent 1:13 classid 1:22 hfsc ls dmax 50ms rate ${QOS_DOWNLOAD_C22}kbit
-      $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:22 handle 22: fq_codel noecn limit 1200 flows 65535 target 5ms
-    $TC class add dev ${DOWNLOAD_IFACE} parent 1:13 classid 1:23 hfsc ls rate ${QOS_DOWNLOAD_C23}kbit
-      $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:23 handle 23: fq_codel noecn limit 1200 flows 65535 target 5ms
-$TC class add dev ${DOWNLOAD_IFACE} parent 1:1 classid 1:3 hfsc ls rate ${QOS_DOWNLOAD_C3}kbit
-  $TC qdisc add dev ${DOWNLOAD_IFACE} parent 1:3 handle 3: fq_codel noecn limit 1200 flows 65535 target 5ms
+  echo ${RATE_C1}' | Maximum interface speed'
+  echo '   '${RATE_C2}' | Maximum internet speed'
+  echo '        '${RATE_C11}' | Priority 1 | DSCP AF41'
+  echo '        '${RATE_C12}' | Priority 2 | DSCP AF42'
+  echo '        '${RATE_C13}' | Other'
+  echo '            '${RATE_C21}' | tcp/80, tcp/443, tcp/21'
+  echo '                '${RATE_C31}' | Browsing | DSCP AF31'
+  echo '                '${RATE_C32}' | Downloading | DSCP AF32'
+  echo '            '${RATE_C22}' | Thrash | DSCP Best Effort'
+  echo '            '${RATE_C23}' | Crew | DSCP AF21'
+  echo '   '${RATE_C3}' | Reserved for interface communication'
 
+  $TC qdisc add dev ${IFACE} stab linklayer ethernet mtu 1500 root handle 1: hfsc default 3
+  $TC class add dev ${IFACE} parent 1: classid 1:1 hfsc sc rate ${RATE_C1}kbit ul rate ${RATE_C1}kbit
+  $TC class add dev ${IFACE} parent 1:1 classid 1:2 hfsc sc rate ${RATE_C2}kbit ul rate ${RATE_C2}kbit
+    $TC class add dev ${IFACE} parent 1:2 classid 1:11 hfsc sc rate ${RATE_C11}kbit
+      $TC qdisc add dev ${IFACE} parent 1:11 handle 11: fq_codel noecn limit 1200 flows 65535 target 5ms
+    $TC class add dev ${IFACE} parent 1:2 classid 1:12 hfsc sc dmax 60ms rate ${RATE_C12}kbit
+      $TC qdisc add dev ${IFACE} parent 1:12 handle 12: fq_codel noecn limit 1200 flows 65535 target 5ms
+    $TC class add dev ${IFACE} parent 1:2 classid 1:13 hfsc ls dmax 100ms rate ${RATE_C13}kbit
+      $TC class add dev ${IFACE} parent 1:13 classid 1:21 hfsc ls rate ${RATE_C21}kbit
+        $TC class add dev ${IFACE} parent 1:21 classid 1:31 hfsc sc rate ${RATE_C31}kbit
+          $TC qdisc add dev ${IFACE} parent 1:31 handle 31: fq_codel noecn limit 1200 flows 65535 target 5ms
+        $TC class add dev ${IFACE} parent 1:21 classid 1:32 hfsc ls dmax 10ms rate ${RATE_C32}kbit
+          $TC qdisc add dev ${IFACE} parent 1:32 handle 32: fq_codel noecn limit 1200 flows 65535 target 5ms
+      $TC class add dev ${IFACE} parent 1:13 classid 1:22 hfsc ls dmax 50ms rate ${RATE_C22}kbit
+        $TC qdisc add dev ${IFACE} parent 1:22 handle 22: fq_codel noecn limit 1200 flows 65535 target 5ms
+      $TC class add dev ${IFACE} parent 1:13 classid 1:23 hfsc ls rate ${RATE_C23}kbit
+        $TC qdisc add dev ${IFACE} parent 1:23 handle 23: fq_codel noecn limit 1200 flows 65535 target 5ms
+  $TC class add dev ${IFACE} parent 1:1 classid 1:3 hfsc ls rate ${RATE_C3}kbit
+    $TC qdisc add dev ${IFACE} parent 1:3 handle 3: fq_codel noecn limit 1200 flows 65535 target 5ms
 
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: protocol arp basic classid 1:3
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 11 fw classid 1:11 # DSCP AF41
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 12 fw classid 1:12 # DSCP AF42
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 31 fw classid 1:31 # DSCP AF31
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 32 fw classid 1:32 # DSCP AF32
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 22 fw classid 1:22 # DSCP Best Effort
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 23 fw classid 1:23 # DSCP AF21
-$TC filter add dev ${DOWNLOAD_IFACE} parent 1: handle 3 fw classid 1:3
+  $TC filter add dev ${IFACE} parent 1: protocol arp basic classid 1:3
+  $TC filter add dev ${IFACE} parent 1: handle 11 fw classid 1:11 # DSCP AF41
+  $TC filter add dev ${IFACE} parent 1: handle 12 fw classid 1:12 # DSCP AF42
+  $TC filter add dev ${IFACE} parent 1: handle 31 fw classid 1:31 # DSCP AF31
+  $TC filter add dev ${IFACE} parent 1: handle 32 fw classid 1:32 # DSCP AF32
+  $TC filter add dev ${IFACE} parent 1: handle 22 fw classid 1:22 # DSCP Best Effort
+  $TC filter add dev ${IFACE} parent 1: handle 23 fw classid 1:23 # DSCP AF21
+  $TC filter add dev ${IFACE} parent 1: handle 3 fw classid 1:3
 
-return 0
+  return 0
 }
-
-export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
 case "$1" in
   start)
-        log_daemon_msg "Committing TC rules" "tc" || true
-        if tc_commit; then
-            log_end_msg 0 || true
-            exit 0
-        else
-            log_end_msg 1 || true
-            exit 1
-        fi
-        ;;
+    echo "Committing TC ruleset for $IFACE"
+    if tc_commit; then
+      echo "Successfully committed ruleset for $IFACE"
+      exit 0
+    else
+      echo "Error committing ruleset for $IFACE" >&2
+      exit 1
+    fi
+    ;;
   stop)
-        log_daemon_msg "Flushing TC rules" "tc" || true
-        if tc_flush; then
-            log_end_msg 0 || true
-            exit 0
-        else
-            log_end_msg 1 || true
-            exit 1
-        fi
-        ;;
-
-  reload|force-reload)
-        log_daemon_msg "Flushing TC rules" "tc" || true
-        if tc_flush; then
-          log_end_msg 0 || true
-        fi
-        log_daemon_msg "Committing TC rules" "tc" || true
-        if tc_commit; then
-            log_end_msg 0 || true
-            exit 0
-        else
-            log_end_msg 1 || true
-            exit 1
-        fi
-        ;;
-
-  restart)
-        log_daemon_msg "Flushing TC rules" "tc" || true
-        if tc_flush; then
-          log_end_msg 0 || true
-        fi
-        log_daemon_msg "Committing TC rules" "tc" || true
-        if tc_commit; then
-            log_end_msg 0 || true
-            exit 0
-        else
-            log_end_msg 1 || true
-            exit 1
-        fi
-        ;;
-
-  status)
-        log_daemon_msg "Checking" "tc"
-        if tc_check; then
-          log_end_msg 0
-          exit 0
-        else
-          log_end_msg 1
-          exit 1
-        fi
-        ;;
+    echo "Flushing TC rules for $IFACE"
+    if tc_flush; then
+      echo "Successfully flushed ruleset for $IFACE"
+      exit 0
+    else
+      echo "Error flushing ruleset for $IFACE" >&2
+      exit 1
+    fi
+    ;;
 
   *)
-        log_action_msg "Usage: /etc/init.d/tc {start|stop|reload|force-reload|restart|status}" || true
-        exit 1
+    echo "Usage: $0 {start|stop} [interface] [speed(kbit)]"
+    exit 1
 esac
 
 exit 0
